/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LoginRouteImport } from './app/login'
import { Route as CallbackRouteImport } from './app/callback'
import { Route as AuthenticatedRouteImport } from './app/_authenticated'
import { Route as IndexRouteImport } from './app/index'
import { Route as AuthenticatedTracksRouteImport } from './app/_authenticated/tracks'
import { Route as AuthenticatedRecentTracksRouteImport } from './app/_authenticated/recentTracks'
import { Route as AuthenticatedPlaylistsRouteImport } from './app/_authenticated/playlists'
import { Route as AuthenticatedArtistsRouteImport } from './app/_authenticated/artists'
import { Route as AuthenticatedTracksIdRouteImport } from './app/_authenticated/tracks.$id'
import { Route as AuthenticatedPlaylistsIdRouteImport } from './app/_authenticated/playlists.$id'
import { Route as AuthenticatedArtistsIdRouteImport } from './app/_authenticated/artists.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTracksRoute = AuthenticatedTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecentTracksRoute =
  AuthenticatedRecentTracksRouteImport.update({
    id: '/recentTracks',
    path: '/recentTracks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaylistsRoute = AuthenticatedPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArtistsRoute = AuthenticatedArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTracksIdRoute = AuthenticatedTracksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTracksRoute,
} as any)
const AuthenticatedPlaylistsIdRoute =
  AuthenticatedPlaylistsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPlaylistsRoute,
  } as any)
const AuthenticatedArtistsIdRoute = AuthenticatedArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedArtistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/artists': typeof AuthenticatedArtistsRouteWithChildren
  '/playlists': typeof AuthenticatedPlaylistsRouteWithChildren
  '/recentTracks': typeof AuthenticatedRecentTracksRoute
  '/tracks': typeof AuthenticatedTracksRouteWithChildren
  '/artists/$id': typeof AuthenticatedArtistsIdRoute
  '/playlists/$id': typeof AuthenticatedPlaylistsIdRoute
  '/tracks/$id': typeof AuthenticatedTracksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/artists': typeof AuthenticatedArtistsRouteWithChildren
  '/playlists': typeof AuthenticatedPlaylistsRouteWithChildren
  '/recentTracks': typeof AuthenticatedRecentTracksRoute
  '/tracks': typeof AuthenticatedTracksRouteWithChildren
  '/artists/$id': typeof AuthenticatedArtistsIdRoute
  '/playlists/$id': typeof AuthenticatedPlaylistsIdRoute
  '/tracks/$id': typeof AuthenticatedTracksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_authenticated/artists': typeof AuthenticatedArtistsRouteWithChildren
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRouteWithChildren
  '/_authenticated/recentTracks': typeof AuthenticatedRecentTracksRoute
  '/_authenticated/tracks': typeof AuthenticatedTracksRouteWithChildren
  '/_authenticated/artists/$id': typeof AuthenticatedArtistsIdRoute
  '/_authenticated/playlists/$id': typeof AuthenticatedPlaylistsIdRoute
  '/_authenticated/tracks/$id': typeof AuthenticatedTracksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/artists'
    | '/playlists'
    | '/recentTracks'
    | '/tracks'
    | '/artists/$id'
    | '/playlists/$id'
    | '/tracks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/artists'
    | '/playlists'
    | '/recentTracks'
    | '/tracks'
    | '/artists/$id'
    | '/playlists/$id'
    | '/tracks/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/login'
    | '/_authenticated/artists'
    | '/_authenticated/playlists'
    | '/_authenticated/recentTracks'
    | '/_authenticated/tracks'
    | '/_authenticated/artists/$id'
    | '/_authenticated/playlists/$id'
    | '/_authenticated/tracks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tracks': {
      id: '/_authenticated/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof AuthenticatedTracksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recentTracks': {
      id: '/_authenticated/recentTracks'
      path: '/recentTracks'
      fullPath: '/recentTracks'
      preLoaderRoute: typeof AuthenticatedRecentTracksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/artists': {
      id: '/_authenticated/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof AuthenticatedArtistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracks/$id': {
      id: '/_authenticated/tracks/$id'
      path: '/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof AuthenticatedTracksIdRouteImport
      parentRoute: typeof AuthenticatedTracksRoute
    }
    '/_authenticated/playlists/$id': {
      id: '/_authenticated/playlists/$id'
      path: '/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof AuthenticatedPlaylistsIdRouteImport
      parentRoute: typeof AuthenticatedPlaylistsRoute
    }
    '/_authenticated/artists/$id': {
      id: '/_authenticated/artists/$id'
      path: '/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof AuthenticatedArtistsIdRouteImport
      parentRoute: typeof AuthenticatedArtistsRoute
    }
  }
}

interface AuthenticatedArtistsRouteChildren {
  AuthenticatedArtistsIdRoute: typeof AuthenticatedArtistsIdRoute
}

const AuthenticatedArtistsRouteChildren: AuthenticatedArtistsRouteChildren = {
  AuthenticatedArtistsIdRoute: AuthenticatedArtistsIdRoute,
}

const AuthenticatedArtistsRouteWithChildren =
  AuthenticatedArtistsRoute._addFileChildren(AuthenticatedArtistsRouteChildren)

interface AuthenticatedPlaylistsRouteChildren {
  AuthenticatedPlaylistsIdRoute: typeof AuthenticatedPlaylistsIdRoute
}

const AuthenticatedPlaylistsRouteChildren: AuthenticatedPlaylistsRouteChildren =
  {
    AuthenticatedPlaylistsIdRoute: AuthenticatedPlaylistsIdRoute,
  }

const AuthenticatedPlaylistsRouteWithChildren =
  AuthenticatedPlaylistsRoute._addFileChildren(
    AuthenticatedPlaylistsRouteChildren,
  )

interface AuthenticatedTracksRouteChildren {
  AuthenticatedTracksIdRoute: typeof AuthenticatedTracksIdRoute
}

const AuthenticatedTracksRouteChildren: AuthenticatedTracksRouteChildren = {
  AuthenticatedTracksIdRoute: AuthenticatedTracksIdRoute,
}

const AuthenticatedTracksRouteWithChildren =
  AuthenticatedTracksRoute._addFileChildren(AuthenticatedTracksRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedArtistsRoute: typeof AuthenticatedArtistsRouteWithChildren
  AuthenticatedPlaylistsRoute: typeof AuthenticatedPlaylistsRouteWithChildren
  AuthenticatedRecentTracksRoute: typeof AuthenticatedRecentTracksRoute
  AuthenticatedTracksRoute: typeof AuthenticatedTracksRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArtistsRoute: AuthenticatedArtistsRouteWithChildren,
  AuthenticatedPlaylistsRoute: AuthenticatedPlaylistsRouteWithChildren,
  AuthenticatedRecentTracksRoute: AuthenticatedRecentTracksRoute,
  AuthenticatedTracksRoute: AuthenticatedTracksRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
